/** Declaration file generated by dts-gen */

export = Medusa;

declare class Medusa {
    constructor(...args: any[]);

    account(...args: any[]): void;

    auth(...args: any[]): void;

    config(...args: any[]): void;

    episode(...args: any[]): void;

    series(...args: any[]): void;

}

declare namespace Medusa {
    namespace prototype {
        function account(...args: any[]): void;

        function auth(...args: any[]): void;

        function config(...args: any[]): void;

        function episode(...args: any[]): void;

        function series(...args: any[]): void;

    }

}
